namespace LightSqlProfiler.Core.Enums
{
    /// <summary>
    /// Reference: https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-trace-setevent-transact-sql?view=sql-server-2017
    /// </summary>
    public enum EventClassType
    {
        /// <summary>
        /// custom (app specific) - not recognized event (internal)
        /// </summary>
        Unknown = 0,

        // custom (app specific) - not internal (custom events)
        Custom = 1,

        /*** AUTO GENERATED:
        SELECT
            CONCAT(
                REPLACE(
                    REPLACE(
                        REPLACE(
                            REPLACE(
                                REPLACE(
                                    REPLACE(t.[Name],
                                    ':', ''),
                                ' ', ''),
                            '(', ''),
                        ')', ''),
                    '/', ''),
                '>', ''),

                ' = ',
                t.trace_event_id,
                ','
            )
        FROM sys.trace_events t
        ***/

        RPCCompleted = 10,
        RPCStarting = 11,
        SQLBatchCompleted = 12,
        SQLBatchStarting = 13,
        AuditLogin = 14,
        AuditLogout = 15,
        Attention = 16,
        ExistingConnection = 17,
        AuditServerStartsAndStops = 18,
        DTCTransaction = 19,
        AuditLoginFailed = 20,
        EventLog = 21,
        ErrorLog = 22,
        LockReleased = 23,
        LockAcquired = 24,
        LockDeadlock = 25,
        LockCancel = 26,
        LockTimeout = 27,
        DegreeofParallelism = 28,
        Exception = 33,
        SPCacheMiss = 34,
        SPCacheInsert = 35,
        SPCacheRemove = 36,
        SPRecompile = 37,
        SPCacheHit = 38,
        SQLStmtStarting = 40,
        SQLStmtCompleted = 41,
        SPStarting = 42,
        SPCompleted = 43,
        SPStmtStarting = 44,
        SPStmtCompleted = 45,
        ObjectCreated = 46,
        ObjectDeleted = 47,
        SQLTransaction = 50,
        ScanStarted = 51,
        ScanStopped = 52,
        CursorOpen = 53,
        TransactionLog = 54,
        HashWarning = 55,
        AutoStats = 58,
        LockDeadlockChain = 59,
        LockEscalation = 60,
        OLEDBErrors = 61,
        ExecutionWarnings = 67,
        ShowplanTextUnencoded = 68,
        SortWarnings = 69,
        CursorPrepare = 70,
        PrepareSQL = 71,
        ExecPreparedSQL = 72,
        UnprepareSQL = 73,
        CursorExecute = 74,
        CursorRecompile = 75,
        CursorImplicitConversion = 76,
        CursorUnprepare = 77,
        CursorClose = 78,
        MissingColumnStatistics = 79,
        MissingJoinPredicate = 80,
        ServerMemoryChange = 81,
        UserConfigurable0 = 82,
        UserConfigurable1 = 83,
        UserConfigurable2 = 84,
        UserConfigurable3 = 85,
        UserConfigurable4 = 86,
        UserConfigurable5 = 87,
        UserConfigurable6 = 88,
        UserConfigurable7 = 89,
        UserConfigurable8 = 90,
        UserConfigurable9 = 91,
        DataFileAutoGrow = 92,
        LogFileAutoGrow = 93,
        DataFileAutoShrink = 94,
        LogFileAutoShrink = 95,
        ShowplanText = 96,
        ShowplanAll = 97,
        ShowplanStatisticsProfile = 98,
        RPCOutputParameter = 100,
        AuditDatabaseScopeGDREvent = 102,
        AuditSchemaObjectGDREvent = 103,
        AuditAddloginEvent = 104,
        AuditLoginGDREvent = 105,
        AuditLoginChangePropertyEvent = 106,
        AuditLoginChangePasswordEvent = 107,
        AuditAddLogintoServerRoleEvent = 108,
        AuditAddDBUserEvent = 109,
        AuditAddMembertoDBRoleEvent = 110,
        AuditAddRoleEvent = 111,
        AuditAppRoleChangePasswordEvent = 112,
        AuditStatementPermissionEvent = 113,
        AuditSchemaObjectAccessEvent = 114,
        AuditBackupRestoreEvent = 115,
        AuditDBCCEvent = 116,
        AuditChangeAuditEvent = 117,
        AuditObjectDerivedPermissionEvent = 118,
        OLEDBCallEvent = 119,
        OLEDBQueryInterfaceEvent = 120,
        OLEDBDataReadEvent = 121,
        ShowplanXML = 122,
        SQLFullTextQuery = 123,
        BrokerConversation = 124,
        DeprecationAnnouncement = 125,
        DeprecationFinalSupport = 126,
        ExchangeSpillEvent = 127,
        AuditDatabaseManagementEvent = 128,
        AuditDatabaseObjectManagementEvent = 129,
        AuditDatabasePrincipalManagementEvent = 130,
        AuditSchemaObjectManagementEvent = 131,
        AuditServerPrincipalImpersonationEvent = 132,
        AuditDatabasePrincipalImpersonationEvent = 133,
        AuditServerObjectTakeOwnershipEvent = 134,
        AuditDatabaseObjectTakeOwnershipEvent = 135,
        BrokerConversationGroup = 136,
        Blockedprocessreport = 137,
        BrokerConnection = 138,
        BrokerForwardedMessageSent = 139,
        BrokerForwardedMessageDropped = 140,
        BrokerMessageClassify = 141,
        BrokerTransmission = 142,
        BrokerQueueDisabled = 143,
        BrokerMirroredRouteStateChanged = 144,
        ShowplanXMLStatisticsProfile = 146,
        Deadlockgraph = 148,
        BrokerRemoteMessageAcknowledgement = 149,
        TraceFileClose = 150,
        DatabaseMirroringConnection = 151,
        AuditChangeDatabaseOwner = 152,
        AuditSchemaObjectTakeOwnershipEvent = 153,
        AuditDatabaseMirroringLogin = 154,
        FTCrawlStarted = 155,
        FTCrawlStopped = 156,
        FTCrawlAborted = 157,
        AuditBrokerConversation = 158,
        AuditBrokerLogin = 159,
        BrokerMessageUndeliverable = 160,
        BrokerCorruptedMessage = 161,
        UserErrorMessage = 162,
        BrokerActivation = 163,
        ObjectAltered = 164,
        Performancestatistics = 165,
        SQLStmtRecompile = 166,
        DatabaseMirroringStateChange = 167,
        ShowplanXMLForQueryCompile = 168,
        ShowplanAllForQueryCompile = 169,
        AuditServerScopeGDREvent = 170,
        AuditServerObjectGDREvent = 171,
        AuditDatabaseObjectGDREvent = 172,
        AuditServerOperationEvent = 173,
        AuditServerAlterTraceEvent = 175,
        AuditServerObjectManagementEvent = 176,
        AuditServerPrincipalManagementEvent = 177,
        AuditDatabaseOperationEvent = 178,
        AuditDatabaseObjectAccessEvent = 180,
        TMBeginTranstarting = 181,
        TMBeginTrancompleted = 182,
        TMPromoteTranstarting = 183,
        TMPromoteTrancompleted = 184,
        TMCommitTranstarting = 185,
        TMCommitTrancompleted = 186,
        TMRollbackTranstarting = 187,
        TMRollbackTrancompleted = 188,
        LockTimeouttimeout0 = 189,
        ProgressReportOnlineIndexOperation = 190,
        TMSaveTranstarting = 191,
        TMSaveTrancompleted = 192,
        BackgroundJobError = 193,
        OLEDBProviderInformation = 194,
        MountTape = 195,
        AssemblyLoad = 196,
        XQueryStaticType = 198,
        QNSubscription = 199,
        QNParametertable = 200,
        QNTemplate = 201,
        QNDynamics = 202,
        BitmapWarning = 212,
        DatabaseSuspectDataPage = 213,
        CPUthresholdexceeded = 214,
        PreConnectStarting = 215,
        PreConnectCompleted = 216,
        PlanGuideSuccessful = 217,
        PlanGuideUnsuccessful = 218,
        AuditFulltext = 235,
    }
}
